server:
  port: 5000
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.201.100
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tCBDijahktTozG7zQcG
    access-key-secret: dd23nlezw3j4mJJTM4WKUD3rAVqx0f
    bucket-domain: http://shaoruilin01.oss-cn-hangzhou.aliyuncs.com
    bucket-name: shaoruilin01
    end-point: http://oss-cn-hangzhou.aliyuncs.com